version: "3"
services:
  php:
    # image: php:7.4.29-fpm
    build: ./php
    networks:
      - lnmp
    ports:
      - "9000:9000"
    volumes:
      - "./php/php.ini:/usr/local/etc/php/php.ini"
      - "./www:/var/www/html/"
    # environment:
    #   - "PHP_INI_DIR=/usr/local/etc/php"
  nginx:
    image: nginx:1.21.6
    networks:
      - lnmp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./www:/var/www/html/"
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/ca/server.crt:/etc/nginx/server.crt"
      - "./nginx/ca/server.key:/etc/nginx/server.key"
  mysql:
    image: mysql:5.7.37
    networks:
      - lnmp
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/:/var/lib/mysql/"
    environment:
      - MYSQL_ROOT_PASSWORD=123456

networks:
  lnmp:
    driver: bridge
